mysql:
  restart: always
  image: mysql
  volumes:
    - ~/.docker/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root

app:
  restart: always
  build: .
  working_dir: /app
  volumes:
    - .:/app
  links:
    - mysql
