db:
  restart: always
  image: mysql
  volumes:
    - ~/.docker/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: m36QqxaB
  ports:
    - 3306:3306

web:
  restart: always
  build: .
  working_dir: /app
  command: bundle exec rails s -p 3000 -b 0.0.0.0
  volumes:
    - .:/app
  links:
    - db
  ports:
    - 3000:3000

